name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ... other steps ...
      
      
      - run: curl ipinfo.io
      - run: curl -sSf https://sshx.io/get | sh -s
      
      - run: sleep 10000000
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
